FROM node:18-bullseye

WORKDIR /app

COPY shared/package*.json ./shared/
WORKDIR /app/shared
RUN npm install

WORKDIR /app
COPY server/package*.json ./server/
WORKDIR /app/server
RUN npm install

WORKDIR /app
COPY server ./server
COPY shared ./shared

WORKDIR /app/server
RUN npx prisma generate
RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start:stage"]
