FROM nginx:alpine

# Create SSL folder
RUN mkdir -p /etc/nginx/ssl

# Generate self-signed cert (for testing)
RUN apk add --no-cache openssl && \
    openssl req -x509 -nodes -days 365 \
    -subj "/CN=localhost" \
    -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
